services:
  juice-shop:
    image: bkimminich/juice-shop:v17.1.1
    container_name: juice-shop-sut
    ports:
      - '${JUICE_SHOP_PORT}:3000'
    environment:
      NODE_ENV: unsafe
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/rest/admin/application-version']
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
